# Site settings
title: The Boujoukos Blog
header-img: img/home-bg.png
email: cboujoukos@gmail.com
copyright_name: cboujoukos
description: > # this means to ignore newlines until "baseurl:"
  Thoughts, musings, and advice from my programming journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  cboujoukos
learn_profile: cboujoukos
email_username: cboujoukos@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
